version: '3'
services:
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:80'
    restart: on-failure
    container_name: client
  to-do-api:
    build: ./cppserver
    ports:
      - '3001:3001'
      - '1935:1935'
      - '8080:8080'
      - '8554:8554'
    restart: on-failure
    container_name: cppserver
